In [36]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns   # graphical
from sklearn.preprocessing import scale
import sklearn.linear_model as lm
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv(r"C:\Users\mpstme.student\Desktop\Iris_main.csv")

In [6]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [8]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [14]:
from statsmodels.multivariate.manova import MANOVA

maov = MANOVA.from_formula(
    "SepalLengthCm + SepalWidthCm + PetalLengthCm + PetalWidthCm ~ Species",
    data=df
)

print(maov.mv_test())

                   Multivariate linear model
================================================================

----------------------------------------------------------------
       Intercept         Value  Num DF  Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda  0.0170 4.0000 144.0000 2080.5278 0.0000
         Pillai's trace  0.9830 4.0000 144.0000 2080.5278 0.0000
 Hotelling-Lawley trace 57.7924 4.0000 144.0000 2080.5278 0.0000
    Roy's greatest root 57.7924 4.0000 144.0000 2080.5278 0.0000
----------------------------------------------------------------

----------------------------------------------------------------
        Species          Value  Num DF  Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda  0.0235 8.0000 288.0000  198.7110 0.0000
         Pillai's trace  1.1872 8.0000 290.0000   52.9486 0.0000
 Hotelling-Lawley trace 32.5495 8.0000 203.4024  583.4914 0.0000
    Roy's greatest root 32.2720 4.0000 145.0000 1169.8585 0.0000
================================================================

In [15]:
ab = pd.read_csv(r"C:\Users\mpstme.student\Desktop\Advertising.csv")

In [16]:
ab

,Unnamed: 0,TV,Radio,Newspaper,Sales,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,230.1,37.8,69.2,22.1,NaN,NaN,6.7502,0.0191,0.0289,0.0011,NaN,21.805088
1,2,44.5,39.3,45.1,10.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,17.2,45.9,69.3,9.3,NaN,NaN,NaN,250.0000,52.0000,NaN,NaN,27.328000
3,4,151.5,41.3,58.5,18.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,180.8,10.8,58.4,12.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,38.2,3.7,13.8,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,197,94.2,4.9,8.1,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,198,177.0,9.3,6.4,12.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,199,283.6,42.0,66.2,25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,200,232.1,8.6,8.7,13.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
lm_fit1 = smf.ols("TV~Radio + Newspaper",ab).fit()
lm_fit1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     TV   R-squared:                       0.003
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.5966
Date:                Thu, 02 Apr 2026   Prob (F-statistic):              0.441
Time:                        11:04:43   Log-Likelihood:                -1173.5
No. Observations:                 200   AIC:                             2351.
Df Residuals:                     198   BIC:                             2358.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    139.6692     11.316     12.342      0.000     117.353     161.985
Radio          0.3169      0.410      0.772      0.441      -0.492       1.126
==============================================================================
Omnibus:                       94.689   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               12.314
Skew:                          -0.084   Prob(JB):                      0.00212
Kurtosis:                       1.796   Cond. No.                         51.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [19]:
lm_fit1 = smf.ols("Radio~TV + Newspaper",ab).fit()
lm_fit1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Radio   R-squared:                       0.127
Model:                            OLS   Adj. R-squared:                  0.118
Method:                 Least Squares   F-statistic:                     14.28
Date:                Thu, 02 Apr 2026   Prob (F-statistic):           1.62e-06
Time:                        11:05:53   Log-Likelihood:                -809.31
No. Observations:                 200   AIC:                             1625.
Df Residuals:                     197   BIC:                             1635.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     15.0430      2.348      6.408      0.000      10.413      19.673
TV             0.0060      0.012      0.523      0.602      -0.017       0.029
Newspaper      0.2401      0.045      5.280      0.000       0.150       0.330
==============================================================================
Omnibus:                       24.135   Durbin-Watson:                   2.091
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                7.505
Skew:                           0.117   Prob(JB):                       0.0235
Kurtosis:                       2.080   Cond. No.                         410.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
lm_fit1 = smf.ols("Newspaper~TV + Radio",ab).fit()
lm_fit1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              Newspaper   R-squared:                       0.127
Model:                            OLS   Adj. R-squared:                  0.118
Method:                 Least Squares   F-statistic:                     14.30
Date:                Thu, 02 Apr 2026   Prob (F-statistic):           1.59e-06
Time:                        11:08:08   Log-Likelihood:                -885.92
No. Observations:                 200   AIC:                             1778.
Df Residuals:                     197   BIC:                             1788.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     17.1466      3.583      4.786      0.000      10.081      24.212
TV             0.0095      0.017      0.560      0.576      -0.024       0.043
Radio          0.5164      0.098      5.280      0.000       0.324       0.709
==============================================================================
Omnibus:                       15.121   Durbin-Watson:                   1.959
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.738
Skew:                           0.610   Prob(JB):                     0.000232
Kurtosis:                       3.723   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [21]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

In [24]:
X = ab[["TV","Radio","Newspaper"]]
X = add_constant(X)
vif_ab = pd.DataFrame()
vif_ab ["Feature"] = X.columns

vif_ab ["VIF"] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

print(vif_ab)

     Feature       VIF
0      const  6.848900
1         TV  1.004611
2      Radio  1.144952
3  Newspaper  1.145187

In [30]:
df1 = pd.read_csv(r"C:\Users\mpstme.student\Desktop\Credit.csv", na_values="?").dropna()

In [31]:
df1

,Unnamed: 0,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560
396,397,13.364,3838,296,5,65,17,Male,No,No,African American,480
397,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
398,399,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0
399,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

In [41]:
le = LabelEncoder()
for col in ['Gender', 'Student', 'Married', 'Ethnicity']:
    df1[col] = le.fit_transform(df1[col])
    
X = df1[['Income', 'Limit' , 'Cards', 'Age', 'Education','Gender', 'Student', 'Married', 'Ethnicity']]
X = add_constant(X)
vif_ab = pd.DataFrame()
vif_ab ["Feature"] = X.columns

vif_ab ["VIF"] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

print(vif_ab)

     Feature        VIF
0      const  44.668678
1     Income   2.773941
2      Limit   2.706481
3      Cards   1.008148
4        Age   1.047966
5  Education   1.013235
6     Gender   1.005270
7    Student   1.020010
8    Married   1.021738
9  Ethnicity   1.007193

In [28]:
df1.columns

Index(['Unnamed: 0', 'Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education',
       'Gender', 'Student', 'Married', 'Ethnicity', 'Balance'],
      dtype='object')

In [42]:
df2 = pd.read_csv(r"C:\Users\mpstme.student\Desktop\HousingData.csv")

In [43]:
df2.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [45]:
X = df2[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'PTRATIO', 'B', 'LSTAT']]
X = add_constant(X)
vif_ab = pd.DataFrame()
vif_ab ["Feature"] = X.columns

vif_ab ["VIF"] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

print(vif_ab)

    Feature         VIF
0     const  623.739542
1      CRIM    1.740243
2        ZN    2.187846
3     INDUS    3.130645
4      CHAS    1.051481
5       NOX    4.492173
6        RM    2.099718
7       AGE    3.171860
8       DIS    3.826923
9       RAD    2.798649
10  PTRATIO    1.802040
11        B    1.372022
12    LSTAT    3.153218

In [46]:
df2

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
390,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
391,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
392,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
393,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0