In [ ]:
import pandas as pd
df=pd.read_csv('/Users/diyamehta/Desktop/SSDI/SSDI M2 LAB (python).csv')
df

   C_name  Var1
0      C    529
1      C    658
2      C    793
3      C    514
4      C    663
5      C    719
6      C    711
7      C    606
8      C    461
9      C    529
10     C    498
11     C    663
12     C    604
13     C    495
14     C    485
15     C    557
16     C    353
17     C    557
18     C    542
19     C    614
20      Q   804
21      Q   630
22      Q   774
23      Q   717
24      Q   679
25      Q   604
26      Q   620
27      Q   697
28      Q   706
29      Q   615
30      Q   492
31      Q   719
32      Q   787
33      Q   699
34      Q   572
35      Q   523
36      Q   584
37      Q   634
38      Q   580
39      Q   624
40      P   672
41      P   531
42      P   443
43      P   596
44      P   602
45      P   502
46      P   659
47      P   689
48      P   675
49      P   512
50      P   691
51      P   733
52      P   698
53      P   776
54      P   561
55      P   572
56      P   469
57      P   581
58      P   679
59      P   532

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1=ols('Var1 ~ C_name',data=df).fit()
annova1=sm.stats.anova_lm(fit1,typ=1)
annova1

            df         sum_sq       mean_sq         F    PR(>F)
C_name     2.0   57512.233333  28756.116667  3.233041  0.046773
Residual  57.0  506983.500000   8894.447368       NaN       NaN

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["Var1"],groups=df["C_name"])
tukey._results_table

In [ ]:
import pandas as pd
df=pd.read_csv('/Users/diyamehta/Desktop/SSDI/Iris1python.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1=ols('SepalLengthCm ~ Species',data=df).fit()
annova1=sm.stats.anova_lm(fit1,typ=1)
annova1

             df     sum_sq    mean_sq           F        PR(>F)
Species     2.0  63.212133  31.606067  119.264502  1.669669e-31
Residual  147.0  38.956200   0.265008         NaN           NaN

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["SepalLengthCm"],groups=df["Species"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["SepalWidthCm"],groups=df["Species"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["PetalLengthCm"],groups=df["Species"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["PetalWidthCm"],groups=df["Species"])
tukey._results_table

In [ ]:
import pandas as pd
df=pd.read_csv('auto.csv')

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1=ols('mpg ~ origin',data=df).fit()
annova1=sm.stats.anova_lm(fit1,typ=1)
annova1

             df        sum_sq      mean_sq           F        PR(>F)
origin      1.0   7609.238012  7609.238012  183.075114  1.811080e-34
Residual  390.0  16209.755458    41.563476         NaN           NaN

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["mpg"],groups=df["origin"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["horsepower"],groups=df["origin"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["displacement"],groups=df["origin"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["horsepower"],groups=df["cylinders"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["mpg"],groups=df["cylinders"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["horsepower"],groups=df["model_year"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["weight"],groups=df["origin"])
tukey._results_table

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
us = df[df['origin'] == 1]['horsepower']

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
japan = df[df['origin'] == 3]['horsepower']

In [ ]:
from scipy.stats import ttest_ind
import numpy as np
from scipy import stats
print(stats.ttest_ind(us,japan,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(8.460994146188728), pvalue=np.float64(4.719469861870472e-16), df=np.float64(322.0))

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1=ols('horsepower~ origin*cylinders',data=df).fit()
annova1=sm.stats.anova_lm(fit1,typ=2)
annova1

                         sum_sq     df           F        PR(>F)
origin               511.138853    1.0    1.196895  2.746219e-01
cylinders         292150.660745    1.0  684.106819  1.178538e-87
origin:cylinders    1427.295141    1.0    3.342188  6.829244e-02
Residual          165697.012863  388.0         NaN           NaN

In [ ]:
df['origin'] = df['origin'].replace({

     1: 'US',

     2: 'Europe',

     3: 'Japan'

 })

In [ ]:
df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,8,307.0,130.0,3504.0,12.0,70,US,18.0
1,8,350.0,165.0,3693.0,11.5,70,US,15.0
2,8,318.0,150.0,3436.0,11.0,70,US,18.0
3,8,304.0,150.0,3433.0,12.0,70,US,16.0
4,8,302.0,140.0,3449.0,10.5,70,US,17.0
...,...,...,...,...,...,...,...,...
387,4,140.0,86.0,2790.0,15.6,82,US,27.0
388,4,97.0,52.0,2130.0,24.6,82,Europe,44.0
389,4,135.0,84.0,2295.0,11.6,82,US,32.0
390,4,120.0,79.0,2625.0,18.6,82,US,28.0
391,4,119.0,82.0,2720.0,19.4,82,US,31.0

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["horsepower"],groups=df["origin"]+df["cylinders"].astype(str))
tukey._results_table

In [ ]:
import pandas as pd
tukey_df = pd.DataFrame(tukey._results_table.data[1:], columns=tukey._results_table.data[0])
true_values = tukey_df[tukey_df['reject'] == True]
highest = true_values.loc[true_values['meandiff'].astype(float).idxmax()]
print(highest)

group1       Japan4
group2          US8
meandiff    82.7213
p-adj           0.0
lower       73.4763
upper       91.9662
reject         True
Name: 29, dtype: object

In [ ]:
from scipy import stats
US8 = df[(df['origin'] == 'US') & (df['cylinders'] == 8)]['horsepower']
Japan4 = df[(df['origin'] == 'Japan') & (df['cylinders'] == 4)]['horsepower']
t_test = stats.ttest_ind(US8, Japan4, equal_var=False)
print(t_test)

TtestResult(statistic=np.float64(25.29602190041859), pvalue=np.float64(1.951003130627451e-57), df=np.float64(157.99654872864093))

In [54]:
import pandas as pd

df = pd.read_csv("HousingData.csv")
df = df.dropna()

In [55]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1=ols('CRIM ~ RAD',data=df).fit()
annova1=sm.stats.anova_lm(fit1,typ=1)
annova1

             df        sum_sq       mean_sq           F        PR(>F)
RAD         1.0  12329.799438  12329.799438  230.691889  2.662608e-41
Residual  392.0  20951.241029     53.447043         NaN           NaN

In [62]:
df["RAD"].unique()

array([ 1,  2,  3,  5,  4,  8,  6,  7, 24])

In [56]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["CRIM"],groups=df["RAD"])
tukey._results_table

In [63]:

C = df[df['RAD'] == 1]['CRIM']
R = df[df['RAD'] == 24]['CRIM']

In [64]:
from scipy.stats import ttest_ind
import numpy as np
from scipy import stats
print(stats.ttest_ind(C,R,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(-3.1956819989098197), pvalue=np.float64(0.9990895265738026), df=np.float64(110.0))

In [ ]:
WHEN RAD =1 CRIM IS LESS,WHCIH MEANS FARTHER FROM HIGHWAY MORE THE CRIME.

In [65]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1=ols('ZN ~ RAD',data=df).fit()
annova1=sm.stats.anova_lm(fit1,typ=1)
annova1

             df         sum_sq       mean_sq         F        PR(>F)
RAD         1.0   20129.553883  20129.553883  38.42171  1.445076e-09
Residual  392.0  205373.086345    523.910935       NaN           NaN

In [66]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.base.model import Model
tukey=pairwise_tukeyhsd(df["ZN"],groups=df["RAD"])
tukey._results_table

In [69]:
C = df[df['RAD'] == 5]['ZN']
R = df[df['RAD'] == 24]['ZN']

In [70]:
from scipy.stats import ttest_ind
import numpy as np
from scipy import stats
print(stats.ttest_ind(C,R,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(5.131370340626224), pvalue=np.float64(3.567735597178528e-07), df=np.float64(188.0))

THIS MEANS 5KM FROM HIGHWAY HAS MORE PLACE FOR PLOTS THAN 24KM AWAY