In [39]:
import pandas as pd
df=pd.read_csv("BostonHousing.csv")
df=df.dropna()
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 501 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     501 non-null    float64
 1   zn       501 non-null    float64
 2   indus    501 non-null    float64
 3   chas     501 non-null    int64
 4   nox      501 non-null    float64
 5   rm       501 non-null    float64
 6   age      501 non-null    float64
 7   dis      501 non-null    float64
 8   rad      501 non-null    int64
 9   tax      501 non-null    int64
 10  ptratio  501 non-null    float64
 11  b        501 non-null    float64
 12  lstat    501 non-null    float64
 13  medv     501 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 58.7 KB

In [42]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('medv ~ chas',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df        sum_sq      mean_sq          F    PR(>F)
chas        1.0   1300.426413  1300.426413  15.705138  0.000085
Residual  499.0  41318.502369    82.802610        NaN       NaN

In [43]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["medv"],groups=df["chas"])
tukey._results_table

In [53]:
a=df[df['chas']==1].medv
b=df[df['chas']==0].medv

In [54]:
from scipy import stats
print(stats.ttest_ind(a,b,equal_var=True,alternative="greater"))

#river income greater than nonriver

TtestResult(statistic=np.float64(3.962970851014706), pvalue=np.float64(4.241202013540866e-05), df=np.float64(499.0))

In [ ]:
rim	zn	indus	chas	nox	rm	age	dis	rad	tax	ptratio	b	lsta

In [60]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('crim ~ chas',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df        sum_sq     mean_sq         F    PR(>F)
chas        1.0    121.341312  121.341312  1.628393  0.202519
Residual  499.0  37183.488204   74.516008       NaN       NaN

In [68]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["crim"],groups=df["chas"])
tukey._results_table

In [69]:
a1=df[df['chas']==1].crim
b1=df[df['chas']==0].crim
print(stats.ttest_ind(a1,b1,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(-1.2760848450228899), pvalue=np.float64(0.8987404200019736), df=np.float64(499.0))

In [63]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('zb ~ chas',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df         sum_sq     mean_sq         F    PR(>F)
chas        1.0     511.776638  511.776638  0.933391  0.334451
Residual  499.0  273600.930947  548.298459       NaN       NaN

In [70]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["zn"],groups=df["chas"])
tukey._results_table

In [72]:
a1=df[df['chas']==1].zn
b1=df[df['chas']==0].zn
print(stats.ttest_ind(a1,b1,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(-0.9661214304821989), pvalue=np.float64(0.8327742947479855), df=np.float64(499.0))

In [73]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('indus ~ chas',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df        sum_sq    mean_sq         F    PR(>F)
chas        1.0     91.400147  91.400147  1.947535  0.163473
Residual  499.0  23418.665161  46.931193       NaN       NaN

In [74]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["indus"],groups=df["chas"])
tukey._results_table

In [75]:
a1=df[df['chas']==1].indus
b1=df[df['chas']==0].indus
print(stats.ttest_ind(a1,b1,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(1.3955411657045154), pvalue=np.float64(0.08173669548048836), df=np.float64(499.0))

In [76]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('nox ~ chas',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df    sum_sq   mean_sq         F   PR(>F)
chas        1.0  0.055124  0.055124  4.108881  0.04319
Residual  499.0  6.694506  0.013416       NaN      NaN

In [77]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["nox"],groups=df["chas"])
tukey._results_table

In [78]:
a1=df[df['chas']==1].nox
b1=df[df['chas']==0].nox
print(stats.ttest_ind(a1,b1,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(2.0270375522880597), pvalue=np.float64(0.021594852290927582), df=np.float64(499.0))

In [79]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('rm ~ chas',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df      sum_sq   mean_sq         F    PR(>F)
chas        1.0    2.082625  2.082625  4.210073  0.040706
Residual  499.0  246.843723  0.494677       NaN       NaN

In [80]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["rm"],groups=df["chas"])
tukey._results_table

In [81]:
a1=df[df['chas']==1].rm
b1=df[df['chas']==0].rm
print(stats.ttest_ind(a1,b1,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(2.0518462563425253), pvalue=np.float64(0.020352951975119327), df=np.float64(499.0))

In [88]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('age ~ chas',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df         sum_sq      mean_sq         F    PR(>F)
chas        1.0    3038.877974  3038.877974  3.839709  0.050609
Residual  499.0  394925.822425   791.434514       NaN       NaN

In [89]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["age"],groups=df["chas"])
tukey._results_table

In [90]:
a1=df[df['chas']==1].age
b1=df[df['chas']==0].age
print(stats.ttest_ind(a1,b1,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(1.9595174615643134), pvalue=np.float64(0.025304250052484746), df=np.float64(499.0))

In [92]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('dis ~ chas',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df       sum_sq    mean_sq         F    PR(>F)
chas        1.0    21.546841  21.546841  4.908533  0.027175
Residual  499.0  2190.445304   4.389670       NaN       NaN

In [93]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["dis"],groups=df["chas"])
tukey._results_table

In [91]:
a1=df[df['chas']==1].dis
b1=df[df['chas']==0].dis
print(stats.ttest_ind(a1,b1,equal_var=True,alternative="greater"))

TtestResult(statistic=np.float64(-2.2155209800436326), pvalue=np.float64(0.9864125181795236), df=np.float64(499.0))

In [57]:

import statsmodels.api as sm
 
from statsmodels.formula.api import ols
fit1 = ols('medv ~ rad*chas',data=df).fit()
anova1=sm.stats.anova_lm(fit1,typ=2)

anova1

                sum_sq     df          F        PR(>F)
rad        6258.089706    1.0  90.665469  7.420877e-20
chas       1250.197660    1.0  18.112517  2.489630e-05
rad:chas    755.504630    1.0  10.945542  1.006328e-03
Residual  34304.908033  497.0        NaN           NaN

In [ ]:
mpg ~ origin*cylinders

In [44]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
fit1 = ols('medv ~ rad',data=df).fit()
anova1 = sm.stats.anova_lm(fit1,typ=1)
anova1

             df        sum_sq      mean_sq          F        PR(>F)
rad         1.0   6308.318459  6308.318459  86.692316  4.029040e-19
Residual  499.0  36310.610324    72.766754        NaN           NaN

In [45]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["medv"],groups=df["rad"])
tukey._results_table