In [1]:
#analysis of variance
# case study of harrassment in IT company
x1=[]  #attitude towards boss

In [13]:
import pandas as pd
df=pd.read_excel('ANOVA.xlsx')
df

        Var  Method
0   Convnce     529
1   Convnce     658
2   Convnce     793
3   Convnce     514
4   Convnce     663
5   Convnce     719
6   Convnce     711
7   Convnce     606
8   Convnce     461
9   Convnce     529
10  Convnce     498
11  Convnce     663
12  Convnce     604
13  Convnce     495
14  Convnce     485
15  Convnce     557
16  Convnce     353
17  Convnce     557
18  Convnce     542
19  Convnce     614
20  Quality     804
21  Quality     630
22  Quality     774
23  Quality     717
24  Quality     679
25  Quality     604
26  Quality     620
27  Quality     697
28  Quality     706
29  Quality     615
30  Quality     492
31  Quality     719
32  Quality     787
33  Quality     699
34  Quality     572
35  Quality     523
36  Quality     584
37  Quality     634
38  Quality     580
39  Quality     624
40    Price     672
41    Price     531
42    Price     443
43    Price     596
44    Price     602
45    Price     502
46    Price     659
47    Price     689
48    Price     675
49    Price     512
50    Price     691
51    Price     733
52    Price     698
53    Price     776
54    Price     561
55    Price     572
56    Price     469
57    Price     581
58    Price     679
59    Price     532

In [16]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

fit1=ols('Method ~ Var', data=df).fit()
anova1=sm.stats.anova_lm(fit1, typ=1)
anova1
# PR(>F) is the P value which is less than 0.05

            df         sum_sq       mean_sq         F    PR(>F)
Var        2.0   57512.233333  28756.116667  3.233041  0.046773
Residual  57.0  506983.500000   8894.447368       NaN       NaN

In [17]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["Method"], groups=df["Var"])
tukey._results_table

In [18]:
import pandas as pd
df=pd.read_csv('auto.csv')
df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,mpg
0,8,307.0,130.0,3504.0,12.0,70,1,18.0
1,8,350.0,165.0,3693.0,11.5,70,1,15.0
2,8,318.0,150.0,3436.0,11.0,70,1,18.0
3,8,304.0,150.0,3433.0,12.0,70,1,16.0
4,8,302.0,140.0,3449.0,10.5,70,1,17.0
...,...,...,...,...,...,...,...,...
387,4,140.0,86.0,2790.0,15.6,82,1,27.0
388,4,97.0,52.0,2130.0,24.6,82,2,44.0
389,4,135.0,84.0,2295.0,11.6,82,1,32.0
390,4,120.0,79.0,2625.0,18.6,82,1,28.0
391,4,119.0,82.0,2720.0,19.4,82,1,31.0

In [21]:
#1 USA, 2 Europe, 3Japan
#mileage
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["mpg"], groups=df["origin"])
tukey._results_table #all were different in mileage

In [22]:
#horsepower
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["horsepower"], groups=df["origin"])
tukey._results_table #USA is different

In [24]:
#displacement
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["displacement"], groups=df["origin"])
tukey._results_table #US is different in displacement

In [25]:
#acceleration
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["acceleration"], groups=df["origin"])
tukey._results_table  #US is different

In [29]:
#cylinders and mileage
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["mpg"], groups=df["cylinders"])
tukey._results_table