In [2]:
import pandas as pd
df=pd.read_excel('bank_case_study.xlsx')
df #balance call the premium customer based on balance

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [36]:
df=df.dropna()

In [39]:
df.isnull().sum()

age                0
job                0
marital            0
education          0
default            0
balance            0
housing            0
loan               0
contact            0
day                0
month              0
duration           0
campaign           0
pdays              0
previous           0
poutcome           0
y                  0
Combined_Factor    0
dtype: int64

In [ ]:
#job,  marital, education, default, housing, loan, cellular, campaign, previous, y

In [40]:
import statsmodels.api as sm #balance and marital
from statsmodels.formula.api import ols
fit=ols('balance ~ C(job) + C(marital) + C(education) + C(default) + C(housing) + C(loan) + C(contact) + campaign + previous + C(y)', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova #job, education, default, loan, marital

                  df        sum_sq       mean_sq          F        PR(>F)
C(job)          11.0  5.477477e+08  4.979524e+07   5.621352  4.928126e-09
C(marital)       2.0  6.649770e+07  3.324885e+07   3.753441  2.351044e-02
C(education)     3.0  1.001948e+08  3.339826e+07   3.770307  1.021906e-02
C(default)       1.0  1.864908e+08  1.864908e+08  21.052821  4.589601e-06
C(housing)       1.0  1.874895e+07  1.874895e+07   2.116557  1.457836e-01
C(loan)          1.0  1.465342e+08  1.465342e+08  16.542154  4.839515e-05
C(contact)       2.0  2.376117e+07  1.188058e+07   1.341191  2.616386e-01
C(y)             1.0  1.294479e+05  1.294479e+05   0.014613  9.037872e-01
campaign         1.0  4.531757e+06  4.531757e+06   0.511587  4.744898e-01
previous         1.0  2.055670e+07  2.055670e+07   2.320632  1.277385e-01
Residual      4496.0  3.982661e+10  8.858232e+06        NaN           NaN

In [41]:
import statsmodels.api as sm # balance vs Job
from statsmodels.formula.api import ols
fit=ols('balance ~ job*education', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova #significantly affects

                   df        sum_sq       mean_sq         F        PR(>F)
job              11.0  5.477477e+08  4.979524e+07  5.581751  5.931776e-09
education         3.0  1.002009e+08  3.340030e+07  3.743976  1.059823e-02
job:education    33.0  3.898727e+08  1.181432e+07  1.324316  1.018840e-01
Residual       4473.0  3.990399e+10  8.921079e+06       NaN           NaN

In [32]:
import statsmodels.api as sm #balance and marital
from statsmodels.formula.api import ols
fit=ols('balance ~ job*marital*education', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova #doesn't significantly affects

,df,sum_sq,mean_sq,F,PR(>F)
job,11.0,5.477477e+08,4.979524e+07,5.626288,4.833673e-09
marital,2.0,6.649770e+07,3.324885e+07,3.756737,2.343496e-02
education,3.0,1.001948e+08,3.339826e+07,3.773618,1.017384e-02
job:marital,22.0,2.383151e+08,1.083250e+07,1.223948,2.148299e-01
job:education,33.0,3.718765e+08,1.126899e+07,1.273265,1.362223e-01
marital:education,6.0,5.204448e+07,8.674080e+06,0.980071,4.368612e-01
job:marital:education,66.0,8.098267e+08,1.227010e+07,1.386380,2.162450e-02
Residual,4391.0,3.886238e+10,8.850461e+06,NaN,NaN

In [42]:
import statsmodels.api as sm #balance and marital
from statsmodels.formula.api import ols
fit=ols('balance ~ job*marital*education*loan', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova #doesn't significantly affects

,df,sum_sq,mean_sq,F,PR(>F)
job,11.0,5.477477e+08,4.979524e+07,5.634063,4.673822e-09
marital,2.0,6.649770e+07,3.324885e+07,3.761928,2.331508e-02
education,3.0,1.001948e+08,3.339826e+07,3.778832,1.010178e-02
loan,1.0,1.661981e+08,1.661981e+08,18.804415,1.481331e-05
job:marital,22.0,2.428261e+08,1.103755e+07,1.248839,1.946032e-01
job:education,33.0,3.740113e+08,1.133368e+07,1.282344,1.295522e-01
marital:education,6.0,5.020657e+07,8.367762e+06,0.946767,4.600327e-01
job:loan,11.0,3.124913e+07,2.840830e+06,0.321425,9.815428e-01
marital:loan,2.0,2.068298e+07,1.034149e+07,1.170084,3.104393e-01
education:loan,3.0,5.352173e+07,1.784058e+07,2.018565,1.091002e-01
job:marital:education,66.0,9.914764e+08,1.502237e+07,1.699700,3.902808e-04
job:marital:loan,22.0,1.360698e+08,6.184990e+06,0.699798,8.443368e-01
job:education:loan,33.0,2.616752e+08,7.929552e+06,0.897186,6.365848e-01
marital:education:loan,6.0,1.068514e+08,1.780857e+07,2.014943,6.024339e-02
job:marital:education:loan,66.0,4.211257e+08,6.380692e+06,0.721941,9.560031e-01
Residual,4319.0,3.817239e+10,8.838248e+06,NaN,NaN

In [49]:
import statsmodels.api as sm #balance and marital
from statsmodels.formula.api import ols
fit=ols('balance ~ job*marital*education*default*loan', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova #doesn't significantly affects

,df,sum_sq,mean_sq,F,PR(>F)
job,11.0,5.477477e+08,4.979524e+07,5.628414,4.807171e-09
marital,2.0,6.649770e+07,3.324885e+07,3.758156,2.340389e-02
education,3.0,1.001948e+08,3.339826e+07,3.775044,1.015555e-02
default,1.0,1.864908e+08,1.864908e+08,21.079269,4.533386e-06
loan,1.0,1.459400e+08,1.459400e+08,16.495769,4.963322e-05
job:marital,22.0,2.366152e+08,1.075523e+07,1.215677,2.219028e-01
job:education,33.0,3.582686e+08,1.085663e+07,1.227137,1.744517e-01
marital:education,6.0,5.136965e+07,8.561609e+06,0.967729,4.453683e-01
job:default,11.0,8.435946e+06,7.669042e+05,0.086684,9.999603e-01
marital:default,2.0,5.223521e+06,2.611760e+06,0.295210,7.443902e-01
education:default,3.0,6.059128e+06,2.019709e+06,0.228290,8.767508e-01
job:loan,11.0,2.846687e+07,2.587897e+06,0.292513,9.874901e-01
marital:loan,2.0,2.274555e+07,1.137277e+07,1.285478,2.766254e-01
education:loan,3.0,6.452504e+07,2.150835e+07,2.431113,6.326408e-02
default:loan,1.0,2.239013e+05,2.239013e+05,0.025308,8.736099e-01
job:marital:education,66.0,7.149590e+08,1.083271e+07,1.224434,1.058556e-01
job:marital:default,22.0,1.384342e+08,6.292462e+06,0.711244,8.326162e-01
job:education:default,33.0,1.123135e+08,3.403440e+06,0.384695,9.994344e-01
marital:education:default,6.0,1.692485e+07,2.820809e+06,0.318839,9.274793e-01
job:marital:loan,22.0,1.037158e+08,4.714353e+06,0.532869,9.626233e-01
job:education:loan,33.0,5.444464e+08,1.649838e+07,1.864831,1.966164e-03
marital:education:loan,6.0,9.660670e+06,1.610112e+06,0.181993,9.818689e-01
job:default:loan,11.0,2.272224e+07,2.065659e+06,0.233484,9.952750e-01
marital:default:loan,2.0,2.653493e+06,1.326746e+06,0.149964,8.607438e-01
education:default:loan,3.0,3.310595e+06,1.103532e+06,0.124733,9.455134e-01
job:marital:education:default,66.0,4.554782e+08,6.901185e+06,0.780049,9.037720e-01
job:marital:education:loan,66.0,3.581398e+08,5.426361e+06,0.613348,9.941850e-01
job:marital:default:loan,22.0,1.821331e+08,8.278776e+06,0.935760,5.464778e-01
job:education:default:loan,33.0,2.254602e+08,6.832127e+06,0.772243,8.212846e-01
marital:education:default:loan,6.0,2.213737e+07,3.689561e+06,0.417035,8.681709e-01
job:marital:education:default:loan,66.0,4.502103e+08,6.821368e+06,0.771027,9.137900e-01
Residual,4271.0,3.778604e+10,8.847118e+06,NaN,NaN

In [46]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["balance"],groups=df["education"])
tukey._results_table

In [47]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["balance"],groups=df["loan"])
tukey._results_table

In [54]:
a = df[(df["education"] == 'primary') & (df["loan"] == "yes")][["balance"]]
b = df[(df["education"] == 'unknown') & (df["loan"] == "yes")][["balance"]]

In [55]:
from scipy import stats
print(stats.ttest_ind(a, b, equal_var=True, alternative="greater"))

TtestResult(statistic=array([-4.2732437]), pvalue=array([0.99997782]), df=array([99.]))

In [73]:

d=df[(df['y']=='no') & (df["education"] == 'unknown') & (df["loan"] == "yes") & (df['default']=='no')]

In [76]:
print(d)

      age         job  marital education default  balance housing loan  \
304    56  management  married   unknown      no      353      no  yes
1069   45  technician   single   unknown      no     7108     yes  yes
1561   54    services  married   unknown      no      386      no  yes
1821   51   housemaid  married   unknown      no    21244      no  yes
3194   28  management   single   unknown      no       81      no  yes
4508   42      admin.  married   unknown      no      642     yes  yes

       contact  day month  duration  campaign  pdays  previous poutcome   y  \
304   cellular   25   jul       171         2     -1         0  unknown  no
1069  cellular   18   nov        53         1    172         3  failure  no
1561  cellular   19   nov        74         1    152         1  success  no
1821  cellular    4   aug       166         2     -1         0  unknown  no
3194  cellular    8   jul       158         1     -1         0  unknown  no
4508   unknown   16   may       509         2     -1         0  unknown  no

         Combined_Factor
304   management_unknown
1069  technician_unknown
1561    services_unknown
1821   housemaid_unknown
3194  management_unknown
4508      admin._unknown

The presence of high-balance customers within the (Unknown Education + Loan group) suggests that balance levels are not solely determined by loan status. Instead, financial standing may be influenced by underlying demographic or occupational factors that are not captured directly in the dataset. This indicates that the relationship between balance and loan status is complex and cannot be explained by a simple linear trend.