In [2]:
import pandas as pd
df=pd.read_csv('iris.csv')
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [15]:
from statsmodels.multivariate.manova import MANOVA
df.columns = ['sepal_length','sepal_width','petal_length','petal_width','variety']
maov = MANOVA.from_formula(
    'sepal_length + sepal_width + petal_length + petal_width ~ variety',
    data=df
)
print(maov.mv_test())

                   Multivariate linear model
================================================================

----------------------------------------------------------------
       Intercept         Value  Num DF  Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda  0.0170 4.0000 144.0000 2086.7720 0.0000
         Pillai's trace  0.9830 4.0000 144.0000 2086.7720 0.0000
 Hotelling-Lawley trace 57.9659 4.0000 144.0000 2086.7720 0.0000
    Roy's greatest root 57.9659 4.0000 144.0000 2086.7720 0.0000
----------------------------------------------------------------

----------------------------------------------------------------
        variety          Value  Num DF  Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda  0.0234 8.0000 288.0000  199.1453 0.0000
         Pillai's trace  1.1919 8.0000 290.0000   53.4665 0.0000
 Hotelling-Lawley trace 32.4773 8.0000 203.4024  582.1970 0.0000
    Roy's greatest root 32.1919 4.0000 145.0000 1166.9574 0.0000
================================================================

In [18]:
import statsmodels.api as sm 
from statsmodels.formula.api import ols
fit=ols('sepal_length ~ variety', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova

             df     sum_sq    mean_sq           F        PR(>F)
variety     2.0  63.212133  31.606067  119.264502  1.669669e-31
Residual  147.0  38.956200   0.265008         NaN           NaN

In [19]:
import statsmodels.api as sm 
from statsmodels.formula.api import ols
fit=ols('sepal_width ~ variety', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova

             df     sum_sq   mean_sq         F        PR(>F)
variety     2.0  11.344933  5.672467  49.16004  4.492017e-17
Residual  147.0  16.962000  0.115388       NaN           NaN

In [20]:
import statsmodels.api as sm 
from statsmodels.formula.api import ols
fit=ols('petal_width ~ variety', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova

             df     sum_sq    mean_sq           F        PR(>F)
variety     2.0  80.413333  40.206667  960.007147  4.169446e-85
Residual  147.0   6.156600   0.041882         NaN           NaN

In [21]:
import statsmodels.api as sm 
from statsmodels.formula.api import ols
fit=ols('petal_length ~ variety', data=df).fit()  
anova=sm.stats.anova_lm(fit, typ=1)
anova

             df    sum_sq     mean_sq            F        PR(>F)
variety     2.0  437.1028  218.551400  1180.161182  2.856777e-91
Residual  147.0   27.2226    0.185188          NaN           NaN

In [26]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["petal_length"],groups=df["variety"])
tukey._results_table

In [27]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["petal_width"],groups=df["variety"])
tukey._results_table

In [28]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["sepal_length"],groups=df["variety"])
tukey._results_table

In [29]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tukey=pairwise_tukeyhsd(df["sepal_width"],groups=df["variety"])
tukey._results_table

#RANKS
 #Petal_length
 #Petal_width
 #Sepal_Length
 #Sepal_width###